version: "3.8"

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=online_video_training
      - POSTGRES_PASSWORD=soytry123
      - POSTGRES_DB=online_video_training
    ports:
      - "5434:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=soytry123@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050

    ports:
      - "5050:5050"
volumes:
  data: