spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/online_video_training
        username: online_video_training
        password: soytry123
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
            mvc:
            pathmatch:
              matching-strategy: ant_path_matcher
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml	
      enabled: true
app:
  jwtSecret: ======================Suy===========================
  jwtExpirationMs: 86400000
mail:
  host: smtp.gmail.com
  port: 587
  username: Boysoy331@gmail.com
  password:  ${MAIL_PASSWORD}
  properties:
  mail:
    smtp:
      auth: true
      starttls:
        enable: true

